services:
  wiremock-demo:
    image: bscmsc/bsc-wire-mock:latest
    ports:
      - "8088:1398"
    volumes:
      - ./wiremock/mappings:/app/mappings
  message_broker:
      image: bitnami/kafka:latest
      hostname: message_broker
      container_name: message_broker
      ports:
        - "9092:9092"
        - "9093:9093"
      environment:
        KAFKA_ENABLE_KRAFT: yes
        KAFKA_CFG_PROCESS_ROLES: broker,controller
        KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_CFG_LISTENERS: PLAINTEXT://:9092, CONTROLLER://:9093
        KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT, PLAINTEXT:PLAINTEXT
        KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        KAFKA_CFG_BROKER_ID: 1
        KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@message_broker:9093
        ALLOW_PLAINTEXT_LISTENER: yes
        KAFKA_CFG_NODE_ID: 1
        KAFKA_KRAFT_CLUSTER_ID: 1

        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0